### ISSUE TITLE
RPi-3B+, bash: /usr/local/bin/picast: No such file or directory

### ISSUE THREAD

**Issue by overclock98** [miurahr/picast#12]
**Describe the bug**
bash: /usr/local/bin/picast: No such file or directory when try to run picast

**Error Message**
pi@raspberrypi:~ $ python3 -m pip install picast
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting picast
  Using cached https://files.pythonhosted.org/packages/c3/7b/85cabed284ea750ecdf311f83d41ae7fe9466ddba0fc6c4070a17661edbe/picast-0.3.2-py3-none-any.whl
Requirement already satisfied: zeroconf in ./.local/lib/python3.7/site-packages (from picast) (0.28.0)
Requirement already satisfied: ifaddr in ./.local/lib/python3.7/site-packages (from picast) (0.1.7)
Installing collected packages: picast
  The script picast is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed picast-0.3.2
pi@raspberrypi:~ $ picast
bash: /usr/local/bin/picast: No such file or directory

**Additional context**
how can I fix this?

**Comment by overclock98** [comment]
so " sudo python3 -m pip install picast" right?

**Comment by overclock98** [comment]
now I'm getting this error:

pi@raspberrypi:~ $ picast
INFO Already set a p2p interface.
INFO Already set a p2p interface.
INFO Register mDNS/SD entry.
INFO Register mDNS/SD entry.
Exception in thread rtsp-server-0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 416, in run
    if self.negotiate():
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 329, in negotiate
    if not self.rtsp_m3():
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 231, in rtsp_m3
    headers = self.get_rtsp_headers()
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 115, in get_rtsp_headers
    headers = self.read_headers()
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 148, in read_headers
    line = self.sock.readline()
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 84, in readline
    more = self.sock.recv(1024)
socket.timeout: timed out

**Comment by miurahr** [comment]
picast cannot understand your clients message a phace M3, this is protocol handshake error.

**Comment by miurahr** [comment]
This is off-topic report.
"command not-found" is resolved.
