### ISSUE TITLE
Rpi-3b+ socket.timeout: timed out when I'm trying to connect to picast

### ISSUE THREAD

**Issue by overclock98** [miurahr/picast#13]
socket.timeout: timed out when I'm trying to connect to picast,
Should I have to instal wpasupplicant_2.4-1+deb9u4_armhf.deb ? I seen it in lazycat. That's why I am asking.

pi@raspberrypi:~ $ picast
INFO Already set a p2p interface.
INFO Already set a p2p interface.
INFO Register mDNS/SD entry.
INFO Register mDNS/SD entry.
Exception in thread rtsp-server-0:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 416, in run
if self.negotiate():
File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 329, in negotiate
if not self.rtsp_m3():
File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 231, in rtsp_m3
headers = self.get_rtsp_headers()
File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 115, in get_rtsp_headers
headers = self.read_headers()
File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 148, in read_headers
line = self.sock.readline()
File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 84, in readline
more = self.sock.recv(1024)
socket.timeout: timed out

**Comment by miurahr** [comment]
Could you post a packet capture?
Or, run `picast --debug` and post debug log.
