### ISSUE TITLE
tvservice not supported on rpi4 rpiOS 64bit

### ISSUE THREAD

**Issue by Snuupy** [miurahr/picast#42]
**Describe the bug**
Hi, I can't get picast to run on rpi4 latest rpiOS 64bit

```
pi@SnuPi:~ $ tvservice
tvservice is not supported when using the vc4-kms-v3d driver.
Similar features are available with standard linux tools
such as modetest from libdrm-tests.
```

Also, it looks like `python-gst-1.0` has been renamed to `python3-gst-1.0` and `gstreamer1.0-omx-rpi gstreamer1.0-omx-rpi-config` are no longer available from the official rpiOS repositories.

Is there any way to get this working?

**Comment by miurahr** [comment]
Thank you for feedback. I tested on rpiOS 64bit and confirm the issue.
`gstreamer1.0-omx-rpi gstreamer1.0-omx-rpi-config` is not mandatory so I'd like to add note for documentation.

picast uses `tvservice` to retrieve supported resolutions on HDMI display, which is advertised in miracast protocol.
We need a command or API. The help message advice us to use `modetest` command in `libdrm-tests` package.

Because picast parses an output of tvservice, it need to parse output of `modetest`.

**Comment by miurahr** [comment]
`modetest` output looks like
```
  modes:
        name refresh (Hz) hdisp hss hse htot vdisp vss vse vtot)
  1024x768 60 1024 1048 1184 1344 768 771 777 806 flags: nhsync, nvsync; type: driver
  800x600 60 800 840 968 1056 600 601 605 628 flags: phsync, pvsync; type: driver
  800x600 56 800 824 896 1024 600 601 603 625 flags: phsync, pvsync; type: driver
  848x480 60 848 864 976 1088 480 486 494 517 flags: phsync, pvsync; type: driver
  640x480 60 640 656 752 800 480 490 492 525 flags: nhsync, nvsync; type: driver
```

**Comment by Snuupy** [comment]
Hi @miurahr, thanks for the help! Is there anything I can provide to help on my end? Do you want me to run modetest on my rpi4 and paste the output here?

**Comment by miurahr** [comment]
> Hi @miurahr, thanks for the help! Is there anything I can provide to help on my end? Do you want me to run modetest on my rpi4 and paste the output here?

It is perfect if you can provide it!  Now working to modify a code to accept modetest command output.

**Comment by Snuupy** [comment]
I didn't have the pi4 plugged into the TV and modetest came up empty. I ran it again after plugging it into the TV and I've attached the output here:

[modetest.txt](https://github.com/miurahr/picast/files/8184517/modetest.txt)

**Comment by miurahr** [comment]
Here is partial result of output

```
pi@raspberrypi4:~ $ modetest |more
trying to open device 'i915'...failed
trying to open device 'amdgpu'...failed
trying to open device 'radeon'...failed
trying to open device 'nouveau'...failed
trying to open device 'vmwgfx'...failed
trying to open device 'omapdrm'...failed
trying to open device 'exynos'...failed
trying to open device 'tilcdc'...failed
trying to open device 'msm'...failed
trying to open device 'sti'...failed
trying to open device 'tegra'...failed
trying to open device 'imx-drm'...failed
trying to open device 'rockchip'...failed
trying to open device 'atmel-hlcdc'...failed
trying to open device 'fsl-dcu-drm'...failed
trying to open device 'vc4'...done
Encoders:
id	crtc	type	possible crtcs	possible clones	
31	80	TMDS	0x00000008	0x00000001
39	0	TMDS	0x00000010	0x00000002
47	0	Virtual	0x00000001	0x00000004

Connectors:
id	encoder	status		name		size (mm)	modes	encoders
32	31	connected	HDMI-A-1       	530x300		32	31
  modes:
	index name refresh (Hz) hdisp hss hse htot vdisp vss vse vtot
  #0 2560x1440 59.95 2560 2608 2640 2720 1440 1443 1448 1481 241500 flags: phsync, nvsync; type: preferred, driver
  #1 3840x2160 30.00 3840 4016 4104 4400 2160 2168 2178 2250 297000 flags: phsync, pvsync; type: driver
  #2 3840x2160 29.97 3840 4016 4104 4400 2160 2168 2178 2250 296703 flags: phsync, pvsync; type: driver
  #3 3840x2160 25.00 3840 4896 4984 5280 2160 2168 2178 2250 297000 flags: phsync, pvsync; type: driver
  #4 3840x2160 24.00 3840 5116 5204 5500 2160 2168 2178 2250 297000 flags: phsync, pvsync; type: driver
  #5 3840x2160 23.98 3840 5116 5204 5500 2160 2168 2178 2250 296703 flags: phsync, pvsync; type: driver
  #6 2560x1440 74.96 2560 2608 2640 2704 1440 1443 1448 1480 300000 flags: phsync, nvsync; type: driver
  #7 1920x1080 60.00 1920 2008 2052 2200 1080 1084 1089 1125 148500 flags: phsync, pvsync; type: userdef, driver
  #8 1920x1080 59.94 1920 2008 2052 2200 1080 1084 1089 1125 148352 flags: phsync, pvsync; type: driver
  #9 1920x1080 50.00 1920 2448 2492 2640 1080 1084 1089 1125 148500 flags: phsync, pvsync; type: driver
  #10 1920x1080 30.00 1920 2008 2052 2200 1080 1084 1089 1125 74250 flags: phsync, pvsync; type: driver
  #11 1920x1080 29.97 1920 2008 2052 2200 1080 1084 1089 1125 74176 flags: phsync, pvsync; type: driver
  #12 1680x1050 59.88 1680 1728 1760 1840 1050 1053 1059 1080 119000 flags: phsync, nvsync; type: driver
  #13 1600x900 60.00 1600 1624 1704 1800 900 901 904 1000 108000 flags: phsync, pvsync; type: driver
  #14 1280x1024 75.02 1280 1296 1440 1688 1024 1025 1028 1066 135000 flags: phsync, pvsync; type: driver
  #15 1280x1024 60.02 1280 1328 1440 1688 1024 1025 1028 1066 108000 flags: phsync, pvsync; type: driver
  #16 1280x800 59.91 1280 1328 1360 1440 800 803 809 823 71000 flags: phsync, nvsync; type: driver
  #17 1152x864 75.00 1152 1216 1344 1600 864 865 868 900 108000 flags: phsync, pvsync; type: driver
  #18 1280x720 60.00 1280 1390 1430 1650 720 725 730 750 74250 flags: phsync, pvsync; type: driver
  #19 1280x720 59.94 1280 1390 1430 1650 720 725 730 750 74176 flags: phsync, pvsync; type: driver
  #20 1280x720 50.00 1280 1720 1760 1980 720 725 730 750 74250 flags: phsync, pvsync; type: driver
  #21 1024x768 75.03 1024 1040 1136 1312 768 769 772 800 78750 flags: phsync, pvsync; type: driver
  #22 1024x768 60.00 1024 1048 1184 1344 768 771 777 806 65000 flags: nhsync, nvsync; type: driver
  #23 832x624 74.55 832 864 928 1152 624 625 628 667 57284 flags: nhsync, nvsync; type: driver
  #24 800x600 75.00 800 816 896 1056 600 601 604 625 49500 flags: phsync, pvsync; type: driver
  #25 800x600 60.32 800 840 968 1056 600 601 605 628 40000 flags: phsync, pvsync; type: driver
  #26 720x576 50.00 720 732 796 864 576 581 586 625 27000 flags: nhsync, nvsync; type: driver
  #27 720x480 60.00 720 736 798 858 480 489 495 525 27027 flags: nhsync, nvsync; type: driver
  #28 720x480 59.94 720 736 798 858 480 489 495 525 27000 flags: nhsync, nvsync; type: driver
  #29 640x480 75.00 640 656 720 840 480 481 484 500 31500 flags: nhsync, nvsync; type: driver
  #30 640x480 60.00 640 656 752 800 480 490 492 525 25200 flags: nhsync, nvsync; type: driver
  #31 640x480 59.94 640 656 752 800 480 490 492 525 25175 flags: nhsync, nvsync; type: driver
  props:
	1 EDID:
		flags: immutable blob
		blobs:
		value:
			00ffffffffffff001e6dc35bbf940900
			081f010380351e78eaf835a8554ea126
			0d5054256b807140818081c0a9c0b300
			d1c08100d1cf565e00a0a0a029503020
			35000f282100001a000000fd00304b1e
			701f010a202020202020000000fc004c
			4720495053205148440a2020000000ff
			003130384e544e484a463930330a0103
			020331f14b0103049012131f225d5e5f
			23090707830100006d030c001000b83e
			200060010203e305c000e60605015353
			5e023a801871382d40582c45000f2821
			00001e011d007251d01e206e2855000f
			282100001e30750090a0a02850302035
			000f282100001a000000000000000000
			000000000000000000000000000000b5
	2 DPMS:
		flags: enum
		enums: On=0 Standby=1 Suspend=2 Off=3
		value: 0
	5 link-status:
		flags: enum
		enums: Good=0 Bad=1
		value: 0
	6 non-desktop:
		flags: immutable range
		values: 0 1
		value: 0
	4 TILE:
		flags: immutable blob
		blobs:

		value:
	37 Colorspace:
		flags: enum
		enums: Default=0 SMPTE_170M_YCC=1 BT709_YCC=2 XVYCC_601=3 XVYCC_709=4 SYCC_601=5 opYCC_601=6 opRGB=7 BT2020_CYCC=8 BT
2020_RGB=9 BT2020_YCC=10 DCI-P3_RGB_D65=11 DCI-P3_RGB_Theater=12
		value: 0
	33 left margin:
		flags: range
		values: 0 100
		value: 0
	34 right margin:
		flags: range
	
```

continues many lines.

**Comment by miurahr** [comment]
@Snuupy  does #43 work for you?

**Comment by Snuupy** [comment]
I can't seem to get the development environment setup properly.

I'm following the instructions here: https://github.com/miurahr/picast/tree/topic-rapi64-testmode#development

Here are the logs:
https://0bin.net/paste/CQQ7VPKq#oWvGPpz7QgdUP3Bm7y1gEYupGs1AFHzc-bGj2pJzAx1

**Comment by miurahr** [comment]
```
$ sudo apt install gstreamer1.0-tools
$ git clone https://github.com/miurahr/picast.git picast
$ cd picast
$ git checkout origin/topic-rapi64-testmode
$ python3 -m venv --system-site-packages venv
$ source venv/bin/activate$ sudo apt install gstreamer1.0-tools
$ git clone https://github.com/miurahr/picast.git picast
$ cd picast
$ python3 -m venv --system-site-packages venv
$ source venv/bin/activate
```

**Comment by Snuupy** [comment]
> ```
> $ git clone https://github.com/miurahr/picast.git picast
> $ cd picast
> $ git checkout origin/topic-rapi64-testmode
> $ python3 -m venv --system-site-packages venv
> ```
then `pip install -e .`, right?
Here's what I get:

https://0bin.net/paste/vmVS8Cr+#Rwp45CiKZvl+bJYkLk37Xh-SE0o0oT+pJAZMV8qEB9c

**Comment by miurahr** [comment]
you can `pip install .`

**Comment by Snuupy** [comment]
Doing a `pip --verbose install .` helped me figure out the error (`AttributeError: install_layout`) which was fixed by deactivating the venv and updating `setuptools` with ` pip3 install setuptools -U`.

Now I'm stuck here:

```
(venv) root@SnuPi:/home/pi/picast# wpa_cli interface
Selected interface 'p2p-dev-wlan0'
Available interfaces:
p2p-dev-wlan0
wlan0
(venv) root@SnuPi:/home/pi/picast# picast --debug
Traceback (most recent call last):
  File "/home/pi/picast/venv/bin/picast", line 8, in <module>
    sys.exit(main())
  File "/home/pi/picast/venv/lib/python3.9/site-packages/picast/__main__.py", line 88, in main
    wifip2p = WifiP2PServer()
  File "/home/pi/picast/venv/lib/python3.9/site-packages/picast/wifip2p.py", line 37, in __init__
    self.set_p2p_interface(R2)
  File "/home/pi/picast/venv/lib/python3.9/site-packages/picast/wifip2p.py", line 113, in set_p2p_interface
    message += "{:s} ".format(it)
TypeError: unsupported format string passed to list.__format__
(venv) root@SnuPi:/home/pi/picast#
```

**Comment by miurahr** [comment]
could you change wifip2p.py", line 113 as `message += "{} ".format(it)` ?

**Comment by Snuupy** [comment]
Swapped it, now I get 

```
(venv) root@SnuPi:/home/pi/picast# picast --debug
Traceback (most recent call last):
  File "/home/pi/picast/venv/bin/picast", line 33, in <module>
    sys.exit(load_entry_point('picast', 'console_scripts', 'picast')())
  File "/home/pi/picast/src/picast/__main__.py", line 88, in main
    wifip2p = WifiP2PServer()
  File "/home/pi/picast/src/picast/wifip2p.py", line 37, in __init__
    self.set_p2p_interface(R2)
  File "/home/pi/picast/src/picast/wifip2p.py", line 115, in set_p2p_interface
    raise WpaException(message)
picast.exceptions.WpaException: Can not create P2P Wifi interface.

Current interfaces are:
p2p-dev-wlan0 ['p2p-dev-wlan0', 'wlan0']
```

**Comment by miurahr** [comment]
picast expect the script create `p2p-wlan0` device not `p2p-dev-wlan0`.
Sometimes it is failed and it sometimes become success.
